# Generated by Django 4.1.3 on 2022-11-26 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Название')),
                ('keywords', models.TextField(blank=True, verbose_name='Ключевые слова')),
                ('annotation', models.TextField(blank=True, verbose_name='Аннотация')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубиковано')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Хештег')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубиковано')),
            ],
            options={
                'verbose_name': 'Хештег',
                'verbose_name_plural': 'Хештеги',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Рубрика')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубиковано')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='ArticleHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубиковано')),
                ('fk_id_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article')),
                ('fk_id_ht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.hashtag')),
            ],
            options={
                'verbose_name': 'НовостьХештег',
                'verbose_name_plural': 'НовостиХештеги',
                'ordering': ['-published'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='rubnum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='news.rubric'),
        ),
    ]
