# Generated by Django 4.1.3 on 2022-12-06 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_myusers_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rubnum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='news.rubric', verbose_name='Рубрика'),
        ),
        migrations.AlterField(
            model_name='articlehashtag',
            name='fk_id_art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlehashtag',
            name='fk_id_ht',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.hashtag', verbose_name='Хештег'),
        ),
    ]
