# Generated by Django 4.1.3 on 2022-12-18 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch_g', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dlcount',
            field=models.IntegerField(blank=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Количество скачиваний не может быть отрицательным')], verbose_name='Кол-во скачиваний'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.TextField(blank=True, validators=[django.core.validators.RegexValidator('^97[89][\\s\\-]?\\d[\\s\\-]?(\\d{4}[\\s\\-]?\\d{4}|\\d{2}[\\s\\-]?\\d{6})[\\s\\-]?\\d$', 'Введите ISBN правильно')], verbose_name='ISBN'),
        ),
    ]
