# Generated by Django 4.1.3 on 2022-12-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ch_g', '0006_alter_additonaluserinfo_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(blank=True, verbose_name='Дата выпуска'),
        ),
    ]
