# Generated by Django 4.1.3 on 2023-01-12 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ch_g', '0010_alter_additonaluserinfo_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='books',
        ),
        migrations.AddField(
            model_name='favourites',
            name='books',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ch_g.book'),
            preserve_default=False,
        ),
    ]
