# Generated by Django 4.1.3 on 2023-01-12 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ch_g', '0011_remove_favourites_books_favourites_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ch_g.book'),
        ),
        migrations.AlterField(
            model_name='favourites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
